version: "3.9"

services:
  pwa:
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL}
      dockerfile: Dockerfile
    container_name: pwa
    restart: unless-stopped
    
    # Porta interna que seu app expõe (ajuste se necessário)
    expose:
      - "3000"

    environment:
      - VITE_PWA_HOST=${VITE_PWA_HOST}
      - VITE_API_URL=${VITE_API_URL}

    labels:
      # Habilita o Traefik
      - "traefik.enable=true"

      # Router
      - "traefik.http.routers.pwa.rule=Host(`${VITE_PWA_HOST}`)"
      - "traefik.http.routers.pwa.entrypoints=websecure"
      - "traefik.http.routers.pwa.service=pwa-service"

      # TLS
      - "traefik.http.routers.pwa.tls=true"
      - "traefik.http.routers.pwa.tls.certresolver=letsencrypt"

      # Load balancer → porta interna
      - "traefik.http.services.pwa-service.loadbalancer.server.port=3000"

    networks:
      - proxy

# Redes externas
networks:
  proxy:
    external: true