/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */

export interface AddAnomaliaDto {
  demandaId: number;
  uuid: string;
  sku: string;
  descricao: string;
  lote: string;
  tipo: string;
  natureza: string;
  causa: string;
  tratado?: boolean;
  quantidadeCaixas: number;
  quantidadeUnidades: number;
  imagens: string[];
}
